"""add_unique_constraints_to_snp_tables

Revision ID: b64d15a4a402
Revises: b7ed0377c138
Create Date: 2025-10-18 16:15:39.691227

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b64d15a4a402'
down_revision = 'b7ed0377c138'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint('tbl_snps_clinvar_ux_rsid_accession', 'tbl_snps_clinvar', ['rsid', 'accession'])
    op.create_unique_constraint('tbl_snps_gwas_ux_rsid_trait_pubmed_id', 'tbl_snps_gwas', ['rsid', 'trait', 'pubmed_id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('tbl_snps_gwas_ux_rsid_trait_pubmed_id', 'tbl_snps_gwas', type_='unique')
    op.drop_constraint('tbl_snps_clinvar_ux_rsid_accession', 'tbl_snps_clinvar', type_='unique')
    # ### end Alembic commands ###
