"""Add SNP GWAS and ClinVar tables

Revision ID: 734ee5ff6a44
Revises: 
Create Date: 2025-10-18 15:28:27.003406

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '734ee5ff6a44'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('tbl_snps_clinvar',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('rsid', sa.Text(), nullable=False),
    sa.Column('gene', sa.Text(), nullable=True),
    sa.Column('accession', sa.Text(), nullable=True),
    sa.Column('clinical_significance', sa.Text(), nullable=True),
    sa.Column('condition', sa.Text(), nullable=True),
    sa.Column('review_status', sa.Text(), nullable=True),
    sa.Column('last_evaluated', sa.Text(), nullable=True),
    sa.Column('number_submitters', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_tbl_snps_clinvar_rsid'), 'tbl_snps_clinvar', ['rsid'], unique=False)
    op.create_table('tbl_snps_gwas',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('rsid', sa.Text(), nullable=False),
    sa.Column('trait', sa.Text(), nullable=False),
    sa.Column('trait_category', sa.Text(), nullable=True),
    sa.Column('pvalue', sa.Text(), nullable=True),
    sa.Column('pvalue_mlog', sa.Float(), nullable=True),
    sa.Column('effect_allele', sa.Text(), nullable=True),
    sa.Column('effect_type', sa.Text(), nullable=True),
    sa.Column('or_or_beta', sa.Text(), nullable=True),
    sa.Column('risk_allele_frequency', sa.Text(), nullable=True),
    sa.Column('study_description', sa.Text(), nullable=True),
    sa.Column('pubmed_id', sa.Text(), nullable=True),
    sa.Column('chromosome', sa.Text(), nullable=True),
    sa.Column('position', sa.Text(), nullable=True),
    sa.Column('mapped_gene', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_tbl_snps_gwas_rsid'), 'tbl_snps_gwas', ['rsid'], unique=False)
    op.create_index(op.f('ix_tbl_snps_gwas_trait_category'), 'tbl_snps_gwas', ['trait_category'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_tbl_snps_gwas_trait_category'), table_name='tbl_snps_gwas')
    op.drop_index(op.f('ix_tbl_snps_gwas_rsid'), table_name='tbl_snps_gwas')
    op.drop_table('tbl_snps_gwas')
    op.drop_index(op.f('ix_tbl_snps_clinvar_rsid'), table_name='tbl_snps_clinvar')
    op.drop_table('tbl_snps_clinvar')
    # ### end Alembic commands ###
