"""revert optional fields to nullable

Revision ID: 7dd144cc84f8
Revises: f31561eab385
Create Date: 2025-10-20 17:25:16.701953

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7dd144cc84f8'
down_revision = 'f31561eab385'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('tbl_category_analyses', sa.Column('updated_date', sa.DateTime(), nullable=False))
    op.alter_column('tbl_genome_analysis_snps', 'clinvar_condition',
               existing_type=sa.TEXT(),
               nullable=True)
    op.alter_column('tbl_genome_analysis_snps', 'clinvar_significance',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('tbl_genome_analysis_snps', 'study_description',
               existing_type=sa.TEXT(),
               nullable=True)
    op.alter_column('tbl_genome_analysis_snps', 'pubmed_id',
               existing_type=sa.TEXT(),
               nullable=True)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('tbl_genome_analysis_snps', 'pubmed_id',
               existing_type=sa.TEXT(),
               nullable=False)
    op.alter_column('tbl_genome_analysis_snps', 'study_description',
               existing_type=sa.TEXT(),
               nullable=False)
    op.alter_column('tbl_genome_analysis_snps', 'clinvar_significance',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('tbl_genome_analysis_snps', 'clinvar_condition',
               existing_type=sa.TEXT(),
               nullable=False)
    op.drop_column('tbl_category_analyses', 'updated_date')
    # ### end Alembic commands ###
