"""add created and updated dates to pubmed papers

Revision ID: 8f9be2305aa9
Revises: 69d4669faeca
Create Date: 2025-10-20 17:12:18.159571

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8f9be2305aa9'
down_revision = '69d4669faeca'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    # Add columns as nullable first
    op.add_column('tbl_pubmed_papers', sa.Column('created_date', sa.DateTime(), nullable=True))
    op.add_column('tbl_pubmed_papers', sa.Column('updated_date', sa.DateTime(), nullable=True))

    # Set default values for existing rows (use fetched_date as fallback)
    op.execute("""
        UPDATE tbl_pubmed_papers
        SET created_date = fetched_date,
            updated_date = fetched_date
        WHERE created_date IS NULL
    """)

    # Now make columns non-nullable
    op.alter_column('tbl_pubmed_papers', 'created_date', nullable=False)
    op.alter_column('tbl_pubmed_papers', 'updated_date', nullable=False)

    # Create indexes
    op.create_index(op.f('ix_tbl_pubmed_papers_created_date'), 'tbl_pubmed_papers', ['created_date'], unique=False)
    op.create_index(op.f('ix_tbl_pubmed_papers_updated_date'), 'tbl_pubmed_papers', ['updated_date'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_tbl_pubmed_papers_updated_date'), table_name='tbl_pubmed_papers')
    op.drop_index(op.f('ix_tbl_pubmed_papers_created_date'), table_name='tbl_pubmed_papers')
    op.drop_column('tbl_pubmed_papers', 'updated_date')
    op.drop_column('tbl_pubmed_papers', 'created_date')
    # ### end Alembic commands ###
