"""add_timestamps_to_snp_tables

Revision ID: b7ed0377c138
Revises: 734ee5ff6a44
Create Date: 2025-10-18 16:12:15.096205

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b7ed0377c138'
down_revision = '734ee5ff6a44'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('tbl_snps_clinvar', sa.Column('created_date', sa.DateTime(), nullable=False, server_default=sa.text('NOW()')))
    op.add_column('tbl_snps_clinvar', sa.Column('updated_date', sa.DateTime(), nullable=False, server_default=sa.text('NOW()')))
    op.add_column('tbl_snps_gwas', sa.Column('created_date', sa.DateTime(), nullable=False, server_default=sa.text('NOW()')))
    op.add_column('tbl_snps_gwas', sa.Column('updated_date', sa.DateTime(), nullable=False, server_default=sa.text('NOW()')))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('tbl_snps_gwas', 'updated_date')
    op.drop_column('tbl_snps_gwas', 'created_date')
    op.drop_column('tbl_snps_clinvar', 'updated_date')
    op.drop_column('tbl_snps_clinvar', 'created_date')
    # ### end Alembic commands ###
