"""Add abstract column to pubmed papers

Revision ID: 490de16f4b15
Revises: 7dd144cc84f8
Create Date: 2025-10-20 18:17:00.372959

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '490de16f4b15'
down_revision = '7dd144cc84f8'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    # Add column as nullable first
    op.add_column('tbl_pubmed_papers', sa.Column('abstract', sa.Text(), nullable=True))
    # Set default value for existing rows (use full_text as fallback)
    op.execute('UPDATE tbl_pubmed_papers SET abstract = full_text WHERE abstract IS NULL')
    # Make column non-nullable
    op.alter_column('tbl_pubmed_papers', 'abstract', nullable=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('tbl_pubmed_papers', 'abstract')
    # ### end Alembic commands ###
