"""add_category_analyses_cache_table

Revision ID: 69d4669faeca
Revises: cadd43006358
Create Date: 2025-10-20 16:51:51.070830

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '69d4669faeca'
down_revision = 'cadd43006358'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('tbl_category_analyses',
    sa.Column('analysis_id', sa.Text(), nullable=False),
    sa.Column('genome_analysis_id', sa.Text(), nullable=False),
    sa.Column('result_id', sa.Text(), nullable=False),
    sa.Column('category', sa.Text(), nullable=False),
    sa.Column('category_description', sa.Text(), nullable=True),
    sa.Column('analysis', sa.Text(), nullable=False),
    sa.Column('papers_used', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('snps_analyzed', sa.Integer(), nullable=False),
    sa.Column('created_date', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('analysis_id')
    )
    op.create_index('idx_category_analyses_genome_result', 'tbl_category_analyses', ['genome_analysis_id', 'result_id'], unique=False)
    op.create_index(op.f('ix_tbl_category_analyses_genome_analysis_id'), 'tbl_category_analyses', ['genome_analysis_id'], unique=False)
    op.create_index(op.f('ix_tbl_category_analyses_result_id'), 'tbl_category_analyses', ['result_id'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_tbl_category_analyses_result_id'), table_name='tbl_category_analyses')
    op.drop_index(op.f('ix_tbl_category_analyses_genome_analysis_id'), table_name='tbl_category_analyses')
    op.drop_index('idx_category_analyses_genome_result', table_name='tbl_category_analyses')
    op.drop_table('tbl_category_analyses')
    # ### end Alembic commands ###
