"""refactor_to_relational_snp_storage_and_manual_categories_only

Revision ID: 25cf36364343
Revises: 6ddc84deacef
Create Date: 2025-10-20 15:42:57.825781

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '25cf36364343'
down_revision = '6ddc84deacef'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('tbl_genome_analysis_snps',
    sa.Column('snp_result_id', sa.Text(), nullable=False),
    sa.Column('result_id', sa.Text(), nullable=False),
    sa.Column('genome_analysis_id', sa.Text(), nullable=False),
    sa.Column('rsid', sa.Text(), nullable=False),
    sa.Column('genotype', sa.Text(), nullable=False),
    sa.Column('chromosome', sa.Text(), nullable=True),
    sa.Column('position', sa.Integer(), nullable=True),
    sa.Column('trait', sa.Text(), nullable=True),
    sa.Column('importance_score', sa.Float(), nullable=False),
    sa.Column('p_value', sa.Text(), nullable=True),
    sa.Column('risk_allele', sa.Text(), nullable=True),
    sa.Column('odds_ratio', sa.Float(), nullable=True),
    sa.Column('risk_allele_frequency', sa.Float(), nullable=True),
    sa.Column('user_has_risk_allele', sa.Boolean(), nullable=True),
    sa.Column('clinvar_condition', sa.Text(), nullable=True),
    sa.Column('clinvar_significance', sa.Integer(), nullable=True),
    sa.Column('study_description', sa.Text(), nullable=True),
    sa.Column('annotation', sa.Text(), nullable=True),
    sa.Column('created_date', sa.DateTime(), nullable=False),
    sa.Column('updated_date', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('snp_result_id')
    )
    op.create_index('idx_genome_analysis_snps_analysis_category', 'tbl_genome_analysis_snps', ['genome_analysis_id', 'result_id'], unique=False)
    op.create_index('idx_genome_analysis_snps_result_importance', 'tbl_genome_analysis_snps', ['result_id', sa.literal_column('importance_score DESC')], unique=False)
    op.create_index(op.f('ix_tbl_genome_analysis_snps_genome_analysis_id'), 'tbl_genome_analysis_snps', ['genome_analysis_id'], unique=False)
    op.create_index(op.f('ix_tbl_genome_analysis_snps_importance_score'), 'tbl_genome_analysis_snps', ['importance_score'], unique=False)
    op.create_index(op.f('ix_tbl_genome_analysis_snps_result_id'), 'tbl_genome_analysis_snps', ['result_id'], unique=False)
    op.create_index(op.f('ix_tbl_genome_analysis_snps_rsid'), 'tbl_genome_analysis_snps', ['rsid'], unique=False)
    op.add_column('tbl_genome_analysis_results', sa.Column('category', sa.Text(), nullable=False))
    op.add_column('tbl_genome_analysis_results', sa.Column('category_description', sa.Text(), nullable=True))
    op.drop_index('ix_tbl_genome_analysis_results_phenotype_group', table_name='tbl_genome_analysis_results')
    op.create_index(op.f('ix_tbl_genome_analysis_results_category'), 'tbl_genome_analysis_results', ['category'], unique=False)
    op.drop_column('tbl_genome_analysis_results', 'phenotype_description')
    op.drop_column('tbl_genome_analysis_results', 'phenotype_group')
    op.drop_column('tbl_genome_analysis_results', 'snps')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('tbl_genome_analysis_results', sa.Column('snps', postgresql.JSONB(astext_type=sa.Text()), autoincrement=False, nullable=False))
    op.add_column('tbl_genome_analysis_results', sa.Column('phenotype_group', sa.TEXT(), autoincrement=False, nullable=False))
    op.add_column('tbl_genome_analysis_results', sa.Column('phenotype_description', sa.TEXT(), autoincrement=False, nullable=True))
    op.drop_index(op.f('ix_tbl_genome_analysis_results_category'), table_name='tbl_genome_analysis_results')
    op.create_index('ix_tbl_genome_analysis_results_phenotype_group', 'tbl_genome_analysis_results', ['phenotype_group'], unique=False)
    op.drop_column('tbl_genome_analysis_results', 'category_description')
    op.drop_column('tbl_genome_analysis_results', 'category')
    op.drop_index(op.f('ix_tbl_genome_analysis_snps_rsid'), table_name='tbl_genome_analysis_snps')
    op.drop_index(op.f('ix_tbl_genome_analysis_snps_result_id'), table_name='tbl_genome_analysis_snps')
    op.drop_index(op.f('ix_tbl_genome_analysis_snps_importance_score'), table_name='tbl_genome_analysis_snps')
    op.drop_index(op.f('ix_tbl_genome_analysis_snps_genome_analysis_id'), table_name='tbl_genome_analysis_snps')
    op.drop_index('idx_genome_analysis_snps_result_importance', table_name='tbl_genome_analysis_snps')
    op.drop_index('idx_genome_analysis_snps_analysis_category', table_name='tbl_genome_analysis_snps')
    op.drop_table('tbl_genome_analysis_snps')
    # ### end Alembic commands ###
