"""add updated_date to genome_analysis_results

Revision ID: 536226bb5bcf
Revises: e9d1ad3088a8
Create Date: 2025-10-20 12:05:19.411534

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '536226bb5bcf'
down_revision = 'e9d1ad3088a8'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    # Add column as nullable first to avoid issues with existing rows
    op.add_column('tbl_genome_analysis_results', sa.Column('updated_date', sa.DateTime(), nullable=True))
    # Set default value for existing rows (use created_date as the initial value)
    op.execute('UPDATE tbl_genome_analysis_results SET updated_date = created_date WHERE updated_date IS NULL')
    # Make the column non-nullable
    op.alter_column('tbl_genome_analysis_results', 'updated_date', nullable=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('tbl_genome_analysis_results', 'updated_date')
    # ### end Alembic commands ###
