"""rename_abstract_to_full_text_in_pubmed_papers

Revision ID: cadd43006358
Revises: c42291d562d7
Create Date: 2025-10-20 16:44:38.192144

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'cadd43006358'
down_revision = 'c42291d562d7'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('tbl_pubmed_papers', sa.Column('full_text', sa.Text(), nullable=True))
    op.alter_column('tbl_pubmed_papers', 'pubmed_id',
               existing_type=sa.VARCHAR(),
               type_=sa.Text(),
               existing_nullable=False)
    op.alter_column('tbl_pubmed_papers', 'journal',
               existing_type=sa.VARCHAR(),
               type_=sa.Text(),
               existing_nullable=True)
    op.alter_column('tbl_pubmed_papers', 'year',
               existing_type=sa.VARCHAR(),
               type_=sa.Text(),
               existing_nullable=True)
    op.drop_index('idx_pubmed_papers_fetched_date', table_name='tbl_pubmed_papers')
    op.create_index(op.f('ix_tbl_pubmed_papers_fetched_date'), 'tbl_pubmed_papers', ['fetched_date'], unique=False)
    op.drop_column('tbl_pubmed_papers', 'abstract')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('tbl_pubmed_papers', sa.Column('abstract', sa.TEXT(), autoincrement=False, nullable=True))
    op.drop_index(op.f('ix_tbl_pubmed_papers_fetched_date'), table_name='tbl_pubmed_papers')
    op.create_index('idx_pubmed_papers_fetched_date', 'tbl_pubmed_papers', ['fetched_date'], unique=False)
    op.alter_column('tbl_pubmed_papers', 'year',
               existing_type=sa.Text(),
               type_=sa.VARCHAR(),
               existing_nullable=True)
    op.alter_column('tbl_pubmed_papers', 'journal',
               existing_type=sa.Text(),
               type_=sa.VARCHAR(),
               existing_nullable=True)
    op.alter_column('tbl_pubmed_papers', 'pubmed_id',
               existing_type=sa.Text(),
               type_=sa.VARCHAR(),
               existing_nullable=False)
    op.drop_column('tbl_pubmed_papers', 'full_text')
    # ### end Alembic commands ###
