"""enforce non-nullable fields in pubmed papers and genome analysis snps

Revision ID: f31561eab385
Revises: 8f9be2305aa9
Create Date: 2025-10-20 17:21:04.457574

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f31561eab385'
down_revision = '8f9be2305aa9'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###

    # Set default values for genome_analysis_snps before making non-nullable
    op.execute("""
        UPDATE tbl_genome_analysis_snps
        SET chromosome = '' WHERE chromosome IS NULL
    """)
    op.execute("""
        UPDATE tbl_genome_analysis_snps
        SET position = 0 WHERE position IS NULL
    """)
    op.execute("""
        UPDATE tbl_genome_analysis_snps
        SET trait = '' WHERE trait IS NULL
    """)
    op.execute("""
        UPDATE tbl_genome_analysis_snps
        SET p_value = '' WHERE p_value IS NULL
    """)
    op.execute("""
        UPDATE tbl_genome_analysis_snps
        SET risk_allele = '' WHERE risk_allele IS NULL
    """)
    op.execute("""
        UPDATE tbl_genome_analysis_snps
        SET user_has_risk_allele = false WHERE user_has_risk_allele IS NULL
    """)
    op.execute("""
        UPDATE tbl_genome_analysis_snps
        SET clinvar_condition = '' WHERE clinvar_condition IS NULL
    """)
    op.execute("""
        UPDATE tbl_genome_analysis_snps
        SET clinvar_significance = 0 WHERE clinvar_significance IS NULL
    """)
    op.execute("""
        UPDATE tbl_genome_analysis_snps
        SET study_description = '' WHERE study_description IS NULL
    """)
    op.execute("""
        UPDATE tbl_genome_analysis_snps
        SET pubmed_id = '' WHERE pubmed_id IS NULL
    """)
    op.execute("""
        UPDATE tbl_genome_analysis_snps
        SET annotation = '' WHERE annotation IS NULL
    """)

    # Set default values for pubmed_papers before making non-nullable
    op.execute("""
        UPDATE tbl_pubmed_papers
        SET title = '' WHERE title IS NULL
    """)
    op.execute("""
        UPDATE tbl_pubmed_papers
        SET full_text = '' WHERE full_text IS NULL
    """)
    op.execute("""
        UPDATE tbl_pubmed_papers
        SET authors = '' WHERE authors IS NULL
    """)
    op.execute("""
        UPDATE tbl_pubmed_papers
        SET journal = '' WHERE journal IS NULL
    """)
    op.execute("""
        UPDATE tbl_pubmed_papers
        SET year = '' WHERE year IS NULL
    """)

    # Now make columns non-nullable
    op.alter_column('tbl_genome_analysis_snps', 'chromosome',
               existing_type=sa.TEXT(),
               nullable=False)
    op.alter_column('tbl_genome_analysis_snps', 'position',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('tbl_genome_analysis_snps', 'trait',
               existing_type=sa.TEXT(),
               nullable=False)
    op.alter_column('tbl_genome_analysis_snps', 'p_value',
               existing_type=sa.TEXT(),
               nullable=False)
    op.alter_column('tbl_genome_analysis_snps', 'risk_allele',
               existing_type=sa.TEXT(),
               nullable=False)
    op.alter_column('tbl_genome_analysis_snps', 'user_has_risk_allele',
               existing_type=sa.BOOLEAN(),
               nullable=False)
    op.alter_column('tbl_genome_analysis_snps', 'clinvar_condition',
               existing_type=sa.TEXT(),
               nullable=False)
    op.alter_column('tbl_genome_analysis_snps', 'clinvar_significance',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('tbl_genome_analysis_snps', 'study_description',
               existing_type=sa.TEXT(),
               nullable=False)
    op.alter_column('tbl_genome_analysis_snps', 'pubmed_id',
               existing_type=sa.TEXT(),
               nullable=False)
    op.alter_column('tbl_genome_analysis_snps', 'annotation',
               existing_type=sa.TEXT(),
               nullable=False)
    op.alter_column('tbl_pubmed_papers', 'title',
               existing_type=sa.TEXT(),
               nullable=False)
    op.alter_column('tbl_pubmed_papers', 'full_text',
               existing_type=sa.TEXT(),
               nullable=False)
    op.alter_column('tbl_pubmed_papers', 'authors',
               existing_type=sa.TEXT(),
               nullable=False)
    op.alter_column('tbl_pubmed_papers', 'journal',
               existing_type=sa.TEXT(),
               nullable=False)
    op.alter_column('tbl_pubmed_papers', 'year',
               existing_type=sa.TEXT(),
               nullable=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('tbl_pubmed_papers', 'year',
               existing_type=sa.TEXT(),
               nullable=True)
    op.alter_column('tbl_pubmed_papers', 'journal',
               existing_type=sa.TEXT(),
               nullable=True)
    op.alter_column('tbl_pubmed_papers', 'authors',
               existing_type=sa.TEXT(),
               nullable=True)
    op.alter_column('tbl_pubmed_papers', 'full_text',
               existing_type=sa.TEXT(),
               nullable=True)
    op.alter_column('tbl_pubmed_papers', 'title',
               existing_type=sa.TEXT(),
               nullable=True)
    op.alter_column('tbl_genome_analysis_snps', 'annotation',
               existing_type=sa.TEXT(),
               nullable=True)
    op.alter_column('tbl_genome_analysis_snps', 'pubmed_id',
               existing_type=sa.TEXT(),
               nullable=True)
    op.alter_column('tbl_genome_analysis_snps', 'study_description',
               existing_type=sa.TEXT(),
               nullable=True)
    op.alter_column('tbl_genome_analysis_snps', 'clinvar_significance',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('tbl_genome_analysis_snps', 'clinvar_condition',
               existing_type=sa.TEXT(),
               nullable=True)
    op.alter_column('tbl_genome_analysis_snps', 'user_has_risk_allele',
               existing_type=sa.BOOLEAN(),
               nullable=True)
    op.alter_column('tbl_genome_analysis_snps', 'risk_allele',
               existing_type=sa.TEXT(),
               nullable=True)
    op.alter_column('tbl_genome_analysis_snps', 'p_value',
               existing_type=sa.TEXT(),
               nullable=True)
    op.alter_column('tbl_genome_analysis_snps', 'trait',
               existing_type=sa.TEXT(),
               nullable=True)
    op.alter_column('tbl_genome_analysis_snps', 'position',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('tbl_genome_analysis_snps', 'chromosome',
               existing_type=sa.TEXT(),
               nullable=True)
    # ### end Alembic commands ###
