"""add_composite_index_rsid_effect_allele

Revision ID: f7e6a32a2eaa
Revises: b64d15a4a402
Create Date: 2025-10-19 21:44:41.289678

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f7e6a32a2eaa'
down_revision = 'b64d15a4a402'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index('idx_snps_gwas_rsid_effect_allele', 'tbl_snps_gwas', ['rsid', 'effect_allele'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('idx_snps_gwas_rsid_effect_allele', table_name='tbl_snps_gwas')
    # ### end Alembic commands ###
