name: deploy
on:
  push:
    branches: [main]
    paths:
      - 'app/**'
      - '.github/workflows/app-deploy.yml'
  workflow_dispatch:
jobs:
  app-deploy:
    runs-on: ubuntu-latest
    env:
      DOCKER_IMAGE: ghcr.io/${{ github.repository }}-app:latest
    steps:
      - name: Check out the repo
        uses: actions/checkout@v4
      - name: Login to GitHub container registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
      - name: Build docker image
        uses: docker/build-push-action@v5
        with:
          context: ./app/
          push: true
          cache-from: type=gha,scope=app
          cache-to: type=gha,mode=max,scope=app
          tags: ${{ env.DOCKER_IMAGE }}
  app-run:
    needs: app-deploy
    runs-on: ubuntu-latest
    env:
      NAME: yieldseeker-app
      DOCKER_IMAGE: ghcr.io/${{ github.repository }}-app:latest
    steps:
      - name: executing remote ssh commands
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.YS_APPBOX_URL }}
          username: ${{ secrets.YS_APPBOX_USER }}
          key: ${{ secrets.YS_APPBOX_SSH_KEY }}
          port: ${{ secrets.YS_APPBOX_PORT }}
          envs: DOCKER_IMAGE,NAME
          script: |
            set -e
            url="beta.yieldseeker.xyz"
            varsFile=~/.${NAME}.vars
            docker pull ${DOCKER_IMAGE}
            docker stop ${NAME} && docker rm ${NAME} || true
            docker run \
                --name ${NAME} \
                --detach \
                --publish-all \
                --restart on-failure \
                --env NAME=${NAME} \
                --env VIRTUAL_HOST=${url} \
                --env LETSENCRYPT_HOST=${url} \
                --env-file ${varsFile} \
                ${DOCKER_IMAGE}
  # app-run-next:
  #   needs: app-deploy
  #   runs-on: ubuntu-latest
  #   env:
  #     NAME: yieldseeker-app-next
  #     DOCKER_IMAGE: ghcr.io/${{ github.repository }}-app:latest
  #   steps:
  #     - name: executing remote ssh commands
  #       uses: appleboy/ssh-action@master
  #       with:
  #         host: ${{ secrets.KIBA_APP_BOX_URL }}
  #         username: ${{ secrets.KIBA_APP_BOX_USER }}
  #         key: ${{ secrets.KIBA_APP_BOX_SSH_KEY }}
  #         port: ${{ secrets.KIBA_APP_BOX_PORT }}
  #         envs: DOCKER_IMAGE,NAME
  #         script: |
  #           set -e
  #           url="yieldseeker-demo-next.kibalabs.com"
  #           varsFile=~/.${NAME}.vars
  #           docker pull ${DOCKER_IMAGE}
  #           docker stop ${NAME} && docker rm ${NAME} || true
  #           docker run \
  #               --name ${NAME} \
  #               --detach \
  #               --publish-all \
  #               --restart on-failure \
  #               --env NAME=${NAME} \
  #               --env VIRTUAL_HOST=${url} \
  #               --env LETSENCRYPT_HOST=${url} \
  #               --env KRT_IS_NEXT=1 \
  #               --env-file ${varsFile} \
  #               ${DOCKER_IMAGE}
